# Coupled host-pathogen-immune dynamics in R.
#
# This compact workflow models:
# - pathogen load
# - immune activity
# - inflammatory or tissue-damage burden
# - repair or resolution
#
# Euler integration is used for article-scale clarity.

dt <- 0.05
time <- seq(0, 30, by = dt)

# Parameters
r <- 0.45       # pathogen growth
c <- 0.12       # immune clearance
alpha <- 0.08   # immune activation by pathogen
delta <- 0.18   # immune decay
gamma <- 0.06   # damage generated by immune activity
rho <- 0.10     # repair or resolution

# Initial states
P <- numeric(length(time))
I <- numeric(length(time))
D <- numeric(length(time))

P[1] <- 50
I[1] <- 2
D[1] <- 0

for (t in 2:length(time)) {
  dP <- r * P[t - 1] - c * I[t - 1] * P[t - 1]
  dI <- alpha * P[t - 1] - delta * I[t - 1]
  dD <- gamma * I[t - 1] - rho * D[t - 1]

  P[t] <- max(0, P[t - 1] + dP * dt)
  I[t] <- max(0, I[t - 1] + dI * dt)
  D[t] <- max(0, D[t - 1] + dD * dt)
}

results <- data.frame(
  time = time,
  pathogen_load = P,
  immune_activity = I,
  damage_burden = D
)

print(tail(round(results, 3), 10))

diagnostics <- data.frame(
  peak_pathogen = max(P),
  peak_immune = max(I),
  peak_damage = max(D),
  final_pathogen = tail(P, 1),
  final_damage = tail(D, 1)
)

print(round(diagnostics, 3))
